/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	kubelessv1beta1 "github.com/kubeless/redis-trigger/pkg/apis/kubeless/v1beta1"
	versioned "github.com/kubeless/redis-trigger/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kubeless/redis-trigger/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/kubeless/redis-trigger/pkg/client/listers/kubeless/v1beta1"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RedisTriggerInformer provides access to a shared informer and lister for
// RedisTriggers.
type RedisTriggerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.RedisTriggerLister
}

type redisTriggerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRedisTriggerInformer constructs a new informer for RedisTrigger type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRedisTriggerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRedisTriggerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRedisTriggerInformer constructs a new informer for RedisTrigger type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRedisTriggerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubelessV1beta1().RedisTriggers(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubelessV1beta1().RedisTriggers(namespace).Watch(context.TODO(), options)
			},
		},
		&kubelessv1beta1.RedisTrigger{},
		resyncPeriod,
		indexers,
	)
}

func (f *redisTriggerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRedisTriggerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *redisTriggerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kubelessv1beta1.RedisTrigger{}, f.defaultInformer)
}

func (f *redisTriggerInformer) Lister() v1beta1.RedisTriggerLister {
	return v1beta1.NewRedisTriggerLister(f.Informer().GetIndexer())
}
