/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/kubeless/kafka-trigger/pkg/apis/kubeless/v1beta1"
	scheme "github.com/kubeless/kafka-trigger/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KafkaTriggersGetter has a method to return a KafkaTriggerInterface.
// A group's client should implement this interface.
type KafkaTriggersGetter interface {
	KafkaTriggers(namespace string) KafkaTriggerInterface
}

// KafkaTriggerInterface has methods to work with KafkaTrigger resources.
type KafkaTriggerInterface interface {
	Create(ctx context.Context, kafkaTrigger *v1beta1.KafkaTrigger, opts v1.CreateOptions) (*v1beta1.KafkaTrigger, error)
	Update(ctx context.Context, kafkaTrigger *v1beta1.KafkaTrigger, opts v1.UpdateOptions) (*v1beta1.KafkaTrigger, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.KafkaTrigger, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.KafkaTriggerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.KafkaTrigger, err error)
	KafkaTriggerExpansion
}

// kafkaTriggers implements KafkaTriggerInterface
type kafkaTriggers struct {
	client rest.Interface
	ns     string
}

// newKafkaTriggers returns a KafkaTriggers
func newKafkaTriggers(c *KubelessV1beta1Client, namespace string) *kafkaTriggers {
	return &kafkaTriggers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kafkaTrigger, and returns the corresponding kafkaTrigger object, and an error if there is any.
func (c *kafkaTriggers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.KafkaTrigger, err error) {
	result = &v1beta1.KafkaTrigger{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kafkatriggers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KafkaTriggers that match those selectors.
func (c *kafkaTriggers) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.KafkaTriggerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.KafkaTriggerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kafkatriggers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kafkaTriggers.
func (c *kafkaTriggers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kafkatriggers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a kafkaTrigger and creates it.  Returns the server's representation of the kafkaTrigger, and an error, if there is any.
func (c *kafkaTriggers) Create(ctx context.Context, kafkaTrigger *v1beta1.KafkaTrigger, opts v1.CreateOptions) (result *v1beta1.KafkaTrigger, err error) {
	result = &v1beta1.KafkaTrigger{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kafkatriggers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kafkaTrigger).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a kafkaTrigger and updates it. Returns the server's representation of the kafkaTrigger, and an error, if there is any.
func (c *kafkaTriggers) Update(ctx context.Context, kafkaTrigger *v1beta1.KafkaTrigger, opts v1.UpdateOptions) (result *v1beta1.KafkaTrigger, err error) {
	result = &v1beta1.KafkaTrigger{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kafkatriggers").
		Name(kafkaTrigger.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kafkaTrigger).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the kafkaTrigger and deletes it. Returns an error if one occurs.
func (c *kafkaTriggers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kafkatriggers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kafkaTriggers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kafkatriggers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched kafkaTrigger.
func (c *kafkaTriggers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.KafkaTrigger, err error) {
	result = &v1beta1.KafkaTrigger{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kafkatriggers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
