/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	v1beta1 "github.com/kubeless/redis-trigger/pkg/apis/kubeless/v1beta1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRedisTriggers implements RedisTriggerInterface
type FakeRedisTriggers struct {
	Fake *FakeKubelessV1beta1
	ns   string
}

var redistriggersResource = schema.GroupVersionResource{Group: "kubeless.io", Version: "v1beta1", Resource: "redistriggers"}

var redistriggersKind = schema.GroupVersionKind{Group: "kubeless.io", Version: "v1beta1", Kind: "RedisTrigger"}

// Get takes name of the redisTrigger, and returns the corresponding redisTrigger object, and an error if there is any.
func (c *FakeRedisTriggers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.RedisTrigger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(redistriggersResource, c.ns, name), &v1beta1.RedisTrigger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.RedisTrigger), err
}

// List takes label and field selectors, and returns the list of RedisTriggers that match those selectors.
func (c *FakeRedisTriggers) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.RedisTriggerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(redistriggersResource, redistriggersKind, c.ns, opts), &v1beta1.RedisTriggerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.RedisTriggerList{ListMeta: obj.(*v1beta1.RedisTriggerList).ListMeta}
	for _, item := range obj.(*v1beta1.RedisTriggerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested redisTriggers.
func (c *FakeRedisTriggers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(redistriggersResource, c.ns, opts))

}

// Create takes the representation of a redisTrigger and creates it.  Returns the server's representation of the redisTrigger, and an error, if there is any.
func (c *FakeRedisTriggers) Create(ctx context.Context, redisTrigger *v1beta1.RedisTrigger, opts v1.CreateOptions) (result *v1beta1.RedisTrigger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(redistriggersResource, c.ns, redisTrigger), &v1beta1.RedisTrigger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.RedisTrigger), err
}

// Update takes the representation of a redisTrigger and updates it. Returns the server's representation of the redisTrigger, and an error, if there is any.
func (c *FakeRedisTriggers) Update(ctx context.Context, redisTrigger *v1beta1.RedisTrigger, opts v1.UpdateOptions) (result *v1beta1.RedisTrigger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(redistriggersResource, c.ns, redisTrigger), &v1beta1.RedisTrigger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.RedisTrigger), err
}

// Delete takes name of the redisTrigger and deletes it. Returns an error if one occurs.
func (c *FakeRedisTriggers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(redistriggersResource, c.ns, name), &v1beta1.RedisTrigger{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRedisTriggers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(redistriggersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.RedisTriggerList{})
	return err
}

// Patch applies the patch and returns the patched redisTrigger.
func (c *FakeRedisTriggers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.RedisTrigger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(redistriggersResource, c.ns, name, pt, data, subresources...), &v1beta1.RedisTrigger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.RedisTrigger), err
}
